button changes
EESTEC-AGH-Krakow/eestec-website-ssa-frontend pull request #24
Opened 2022-09-25 22:04 UTC by Slawska

2022-09-26 17:18 UTC, Elgirhath requested changes

2022-09-29 20:39 UTC, Slawska commented on src/views/Home.vue
> +
zrobione

2022-09-29 20:43 UTC, Slawska commented on src/components/Speaker.vue
> +                    <b-button class="justify-self-end btn-prelegent" v-b-modal.modal-speaker @click="changeSpeaker(speaker)">więcej</b-button>
zrobione

2022-09-29 20:59 UTC, Slawska commented on src/components/Speaker.vue
> +                <b-card-img :src="speaker.image" class="rounded-circle mb-4" v-b-modal.modal-speaker @click="changeSpeaker(speaker)" ></b-card-img>
zrobione

2022-09-29 21:01 UTC, Slawska commented
wszystko poprawione według instrukcji

2022-09-29 21:57 UTC, Elgirhath commented on src/components/Speaker.vue
> +                <b-card-img :src="speaker.image" class="rounded-circle mb-4" v-b-modal.modal-speaker @click="changeSpeaker(speaker)" ></b-card-img>
biutiful!
a jeszcze ze zdjęcia można usunąć ten @click jeśli jest na całości?

2022-09-29 21:57 UTC, Elgirhath commented on src/components/Speaker.vue
> +                <b-card-img :src="speaker.image" class="rounded-circle mb-4" v-b-modal.modal-speaker @click="changeSpeaker(speaker)" ></b-card-img>
o szit, oznaczyłem jakiegoś typa przez przypadek XD

2022-09-29 21:58 UTC, Elgirhath approved these changes
Approoove, jak będziesz mergowała to zrób proszę squash, to wszystko wejdzie wtedy jako jeden commit ;)

2022-09-30 20:27 UTC, merged